In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('GOOG.csv')

In [3]:
df

,Date,Open,High,Low,Close,Adj Close,Volume
0,2013-11-26,520.911987,527.320313,518.100281,525.785278,525.785278,4602200
1,2013-11-27,527.583557,530.549316,526.575134,528.120117,528.120117,2261700
2,2013-11-29,527.648132,529.863770,526.301941,526.371460,526.371460,2401000
3,2013-12-02,528.318787,529.729614,521.984985,523.832947,523.832947,2764200
4,2013-12-03,522.079407,528.283997,521.120605,523.226929,523.226929,3373900
5,2013-12-04,522.288025,528.552307,521.607422,525.671021,525.671021,2398600
6,2013-12-05,525.184204,526.406250,522.148926,525.253723,525.253723,2282000
7,2013-12-06,531.438477,531.542847,526.614868,531.478271,531.478271,2876100
8,2013-12-09,532.034607,537.658081,530.559204,535.586548,535.586548,2984400
9,2013-12-10,534.597961,542.625732,534.349548,538.825439,538.825439,3731800
10,2013-12-11,540.186584,542.133911,534.111145,535.164246,535.164246,3445800
11,2013-12-12,536.296875,537.971008,531.046082,531.522949,531.522949,3213600
12,2013-12-13,534.225403,534.667480,525.526978,526.967590,526.967590,4352800
13,2013-12-16,528.562195,533.872681,527.573669,533.023193,533.023193,3224800
14,2013-12-17,532.943726,536.888062,530.738037,531.473267,531.473267,3091300
15,2013-12-18,532.461853,538.969543,526.098267,538.870178,538.870178,4449300
16,2013-12-19,536.893005,542.466797,536.053467,539.600403,539.600403,3353000
17,2013-12-20,540.633728,547.027100,540.484680,546.753906,546.753906,6565600
18,2013-12-23,550.340576,554.294861,548.989380,553.947083,553.947083,3465500
19,2013-12-24,553.882507,554.016663,550.469727,552.327637,552.327637,1477800
20,2013-12-26,553.405640,555.884521,550.762817,555.119507,555.119507,2692900
21,2013-12-27,556.381287,556.520386,552.874084,555.586426,555.586426,3159800
22,2013-12-30,556.550171,556.629639,550.926758,551.145325,551.145325,2488100
23,2013-12-31,552.526367,556.878052,549.555664,556.734009,556.734009,2733400
24,2014-01-02,554.125916,555.263550,550.549194,552.963501,552.963501,3666400
25,2014-01-03,553.897461,554.856201,548.894958,548.929749,548.929749,3355000
26,2014-01-06,552.908875,555.814941,549.645081,555.049927,555.049927,3561600
27,2014-01-07,558.865112,566.162659,556.957520,565.750366,565.750366,5138400
28,2014-01-08,569.297241,569.953003,562.983337,566.927673,566.927673,4514100
29,2014-01-09,568.025513,568.413025,559.143311,561.468201,561.468201,4196000
...,...,...,...,...,...,...,...
1229,2018-10-15,1108.910034,1113.446045,1089.000000,1092.250000,1092.250000,1372400
1230,2018-10-16,1104.589966,1124.219971,1102.500000,1121.280029,1121.280029,1928500
1231,2018-10-17,1126.459961,1128.989990,1102.189941,1115.689941,1115.689941,1467200
1232,2018-10-18,1121.839966,1121.839966,1077.089966,1087.969971,1087.969971,2094500
1233,2018-10-19,1093.369995,1110.359985,1087.750000,1096.459961,1096.459961,1267600
1234,2018-10-22,1103.060059,1112.229980,1091.000000,1101.160034,1101.160034,1514200
1235,2018-10-23,1080.890015,1107.890015,1070.000000,1103.689941,1103.689941,1848700
1236,2018-10-24,1104.250000,1106.119995,1048.739990,1050.709961,1050.709961,1982400
1237,2018-10-25,1071.790039,1110.979980,1069.550049,1095.569946,1095.569946,2545800
1238,2018-10-26,1037.030029,1106.530029,1034.089966,1071.469971,1071.469971,4187600
1239,2018-10-29,1082.469971,1097.040039,995.830017,1020.080017,1020.080017,3880700
1240,2018-10-30,1008.460022,1037.489990,1000.750000,1036.209961,1036.209961,3212700
1241,2018-10-31,1059.810059,1091.939941,1057.000000,1076.770020,1076.770020,2529800
1242,2018-11-01,1075.800049,1083.974976,1062.459961,1070.000000,1070.000000,1482000
1243,2018-11-02,1073.729980,1082.974976,1054.609985,1057.790039,1057.790039,1839000
1244,2018-11-05,1055.000000,1058.469971,1021.239990,1040.089966,1040.089966,2441400
1245,2018-11-06,1039.479980,1064.344971,1038.069946,1055.810059,1055.810059,1233300
1246,2018-11-07,1069.000000,1095.459961,1065.900024,1093.390015,1093.390015,2058400
1247,2018-11-08,1091.380005,1093.270020,1072.204956,1082.400024,1082.400024,1488200
1248,2018-11-09,1073.989990,1075.560059,1053.109985,1066.150024,1066.150024,1343200
1249,2018-11-12,1061.390015,1062.119995,1031.000000,1038.630005,1038.630005,1471800
1250,2018-11-13,1043.290039,1056.604980,1031.150024,1036.050049,1036.050049,1513700
1251,2018-11-14,1050.000000,1054.563965,1031.000000,1043.660034,1043.660034,1565900
1252,2018-11-15,1044.709961,1071.849976,1031.780029,1064.709961,1064.709961,1836100
1253,2018-11-16,1059.410034,1067.000000,1048.979980,1061.489990,1061.489990,1658100
1254,2018-11-19,1057.199951,1060.790039,1016.260010,1020.000000,1020.000000,1858600
1255,2018-11-20,1000.000000,1031.739990,996.020020,1025.760010,1025.760010,2449100
1256,2018-11-21,1036.760010,1048.560059,1033.469971,1037.609985,1037.609985,1534300
1257,2018-11-23,1030.000000,1037.589966,1022.398987,1023.880005,1023.880005,691500
1258,2018-11-26,1038.349976,1049.310059,1033.910034,1048.619995,1048.619995,1850400